In [1]:
import pandas as pd

In [8]:
df = pd.read_excel('Online_Retail.xlsx')

In [9]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [11]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
df.shape

(541909, 8)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [16]:
df[['Quantity', 'UnitPrice']].describe()

            Quantity      UnitPrice
count  541909.000000  541909.000000
mean        9.552250       4.611114
std       218.081158      96.759853
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

In [28]:
c_invoices = df[df['InvoiceNo'].astype(str).str.startswith('C')]
print(f"{len(c_invoices):,}")

8,872

In [18]:
df = df.dropna(subset='CustomerID')

In [19]:
df = df.drop_duplicates()

In [23]:
returns = df[df['Quantity'] < 0].copy()

In [24]:
len(returns)

8872

In [26]:
real_sales = df[(df['Quantity']> 0) & (df['UnitPrice'] > 0)].copy()
real_sales

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [31]:
df.shape

(401604, 8)

In [32]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [33]:
df['TotalPrice'].describe()

count    401604.000000
mean         20.613638
std         430.352218
min     -168469.600000
25%           4.250000
50%          11.700000
75%          19.800000
max      168469.600000
Name: TotalPrice, dtype: float64

In [34]:
snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)
df['InvoiceDate'].max()

Timestamp('2011-12-09 12:50:00')

In [35]:
snapshot_date

Timestamp('2011-12-10 12:50:00')

In [36]:
rfm = df.groupby('CustomerID').agg(
    Recency = ('InvoiceDate', lambda x: snapshot_date - x.max()),
    Frequency = ('InvoiceNo', 'nunique'),
    Monetary = ('TotalPrice', 'sum')
)

In [39]:
print(f"\nRFM cədvəli: {rfm.shape[0]:,} müştəri × {rfm.shape[1]} sütun")
rfm.head()

RFM cədvəli: 4,372 müştəri × 3 sütun

                     Recency  Frequency  Monetary
CustomerID
12346.0    326 days 02:33:00          2      0.00
12347.0      2 days 20:58:00          7   4310.00
12348.0     75 days 23:37:00          4   1797.24
12349.0     19 days 02:59:00          1   1757.55
12350.0    310 days 20:49:00          1    334.40

In [40]:
rfm[['Recency', 'Frequency', 'Monetary']].describe()

                        Recency    Frequency       Monetary
count                      4372  4372.000000    4372.000000
mean    92 days 13:37:53.302836     5.075480    1893.531433
std    100 days 18:30:05.700066     9.338754    8218.696204
min             1 days 00:00:00     1.000000   -4287.630000
25%            17 days 03:20:30     1.000000     291.795000
50%            50 days 20:53:30     3.000000     644.070000
75%           143 days 21:28:30     5.000000    1608.335000
max           374 days 02:57:00   248.000000  279489.020000